---
site_name: Cisco XRv9k Segment Routing
site_description: A brief look at Segment Rotuing and TI-LFA on Cisco XRv9k 
site_author: Hemant Sharma
site_url: https://hmntsharma.github.io/cisco-segment-routing

repo_url: https://github.com/hmntsharma/cisco-segment-routing
repo_name: hmntsharma/cisco-segment-routing
edit_uri: ""

theme:
  name: material
  palette:
    primary: black
    accent: red
  icon:
    logo: material/router
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - toc.integrate 

nav:
  - Introduction : index.md
  - Getting Started:
    -  IP Address: ip_add.md
    -  Routing (ISIS): isis.md
    -  MPLS (LDP): ldp.md
  - Segment Routing: sr_intro.md
  - SR - LDP Interworking: sr_ldp_inter.md
  - TI-LFA: tilfa.md
  - TI-LFA Scenarios:
    -  Zero Segment TI-LFA: zs_tilfa.md
    -  Single Segment TI-LFA: ss_tilfa.md
    -  Double Segment TI-LFA: ds_tilfa.md
  - Microloop Avoidance: micro_loop_avoidance.md
  - MPLS Traffic-Eng: mpls_traffic_eng.md
  - TI-LFA (Node and SRLG Protection):
    -  Preparation: tilfa_node_srlg_prep.md
    -  Node Protection: tilfa_node.md
    -  Local SRLG-Disjoint Protection: tilfa_local_srlg.md
    -  Global Weighted SRLG Protection: tilfa_gw_srlg.md
    -  Node + SRLG Protection: tilfa_node_srlg.md
  - TI-LFA Tiebreaker (Link vs Node vs SRLG): tilfa_link_node_srlg.md

